name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        id: release_create
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
      - name: Upload asset to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_create.outputs.upload_url }}
          asset_path: ./Release.txt
          asset_name: Release.txt
          asset_content_type: application/zip
