name: "ZallDataSDK CI"

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
jobs:
  Build:
    name: Build
    runs-on: macos-11
    if: startsWith(github.ref, 'refs/tags/')
    env:
      SCHEME_NAME: ZallDataSDK
      DEVELOPER_DIR: /Applications/Xcode_13.0.app
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync Library Version
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          export git_version=$(git describe --tags `git rev-list --tags --max-count=1` | grep -o "\d.*")
          agvtool new-marketing-version $git_version
      - name: Build as static Library # carthage build --archive
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          carthage build --archive
      - name: Version Tag Config
        id: version_tag
        run: |
          last_log=$(git show -s --format=%s)
          version_number=$(echo $last_log -Eo  | grep "v[0-9]+\.[0-9]+.*")
          be_version=$(echo $(git tag) | grep $version_number)
          if [[ $be_version ]]; then echo "::set-output name=version_number::$(())"; else echo "::set-output name=version_number::$((version_number))"; fi
      - name: Pack Option
        if: startsWith(${{ steps.version_tag.outputs.version_number }},'v')
        run: |
          git_version=$(${{ steps.version_tag.outputs.version_number }} | grep -o "\d.*")
          agvtool new-marketing-version $git_version
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "v$git_version"
          git tag -a "v$git_version" -m "v$git_version"
      - name: Git Push
        if: startsWith(${{ steps.version_tag.outputs.version_number }},'v')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   with:
      #     files: ${{ env.SCHEME_NAME }}.framework.zip

      # - name: Deploy to Cocoapods
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: |
      #     set -eo pipefail
      #     export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | grep -o "\d.*")

      #     pod lib lint --allow-warnings
      #     pod trunk push --allow-warnings
      #   env:
      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
